#!/bin/sh

set -e

adduser --system --home /var/lib/centreon-broker --no-create-home --group centreon-broker
adduser centreon-broker centreon-engine
chown -R centreon-broker:centreon-broker /var/lib/centreon-broker /var/log/centreon-broker

#DEBHELPER#
